### ISSUE TITLE
Rubygems 'sidekiq-worker_stats' version is older than github version

### ISSUE THREAD

**Issue by DCrow** [whitesmith/sidekiq-worker_stats#20]
https://rubygems.org/gems/sidekiq-worker_stats/versions
Shows versions up to 0.0.11
Would be great if the new version was also uploaded.

**Comment by jsantos** [comment]
@DCrow I'm aware of that, but I don't have access to the RubyGems account to update this :(

@adbjesus could you hand it over to me or @Onumis?

**Comment by adbjesus** [comment]
Pushed new version (sorry for the delay, I completely missed this issue, and only with the recent pull request did I see this).
